# Generated by Django 4.1.7 on 2023-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(default=11, max_length=150),
            preserve_default=False,
        ),
    ]
