# Generated by Django 4.1.7 on 2023-03-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_order_address_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1212, on_delete=django.db.models.deletion.CASCADE, to='Accounts.address'),
            preserve_default=False,
        ),
    ]
